#!/usr/bin/env ruby

begin
  require 'pre-commit'
  PreCommit.run
rescue LoadError
  $stderr.puts "pre-commit: WARNING: Skipping checks because the pre-commit gem is not installed. (Did you change your Ruby version?)"
  exit(0)
rescue SystemExit => e
  exit(e.status)
end
