#!/usr/bin/env ruby

if system("which rvm > /dev/null")
  cmd = "rvm default do ruby -rrubygems "
else
  cmd = "ruby -rrubygems "
end

if !system("#{cmd} -rpre-commit -e '' 2> /dev/null")
  $stderr.puts "pre-commit: WARNING: It looks like you've upgraded your Ruby version."
  $stderr.puts "The pre-commit gem is not installed, skipping checks."
  exit(0)
end

cmd << %Q{-e "require 'pre-commit'; PreCommit.run"}

exit(system(cmd) ? 0 : 1)
