#!/usr/bin/env ruby

if system("which rvm > /dev/null")
  cmd = "rvm default do ruby -rrubygems "
else
  cmd = "ruby -rrubygems "
end

cmd << %Q{-e "require 'pre-commit'; PreCommit.run"}

exit(system(cmd) ? 0 : 1)
